### ISSUE TITLE
Hide block when there's no place on a bar

### ISSUE THREAD

**Issue by ivankovnatsky** [greshake/i3status-rust#1205] opened 2021-05-01 17:26 UTC
The use case: on an external big screen I can easily fit all my blocks, though when I'm my laptop it surely hides those blocks on the left.

Would be cool to be able to flag blocks that are less important and hide them when there's no free space on a bar.

Please point me, if I missed a way to accomplish this or similar behavior. 

```
[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
hide_on_bar_full = true
```

**Comment by MaxVerevkin** [comment] 2021-05-01 17:30
Relevant issue: #676 
Relevant PR: #703

**Comment by GladOSkar** [comment] 2021-05-01 21:14
AFAIK this is not reasonably possible for us to do until `i3/i3#4113` is implemented, which, knowing i3's development cycle will still take a while.

Until then i think we can only switch all blocks to short mode at once which might allow for some workarounds (make the short mode for all the "important" blocks the same as their long mode to only shorten non-important ones?)

**Comment by GladOSkar** [comment] 2021-05-01 21:16
Actually nvm that feature request is suggesting something a bit different from what you're asking. But still, this definitely requires some interaction with the DE/WM not currently possible with i3 without workarounds

**Comment by GladOSkar** [comment] 2021-05-01 21:23
Also, with basically all blocks having been reworked to use format strings and a unified click interface being in the works (or done, not sure?) it's probably worth revisiting #676 (and #703) since this might have become easier to do

**Comment by GladOSkar** [comment] 2021-05-01 22:48
Okay i just took a quick look at trying to implement this and the main problem i ran into was the following: `i3status-rust` has no information about whether a block will be short or not and we have to pass a single big list of widgets to `i3`, some of which should now get a `short_text` attribute.

But `format_short` would be specified on a block level. Since a block contains a series of widgets built from the format string, it's really hard to build one widget list from 2 format strings, since we can't really correlate widgets of the format strings together between the 2.

So another idea would be integrating this into the format string syntax as a modifier for the placeholders (like `{speed_down?}` means can be hidden). But that would probably limit the functionality quite a bit because it can't be used to, say, shorten the decimal precision or hide text when becoming short.

The next idea is even hackier: For the short format, add entirely new widgets to the list in addition to the full format ones, and set their `full_text` and the full format widget's `short_text` to be empty (`""`). This should make the short format invisible normally, and the full format invisible when `short_text` is in use by the DE/WM. But then again this approach would not work if the DE switched to the `short_text`s progressively instead of all at once.

So I'm out of ideas for now, anyone else?

**Comment by MaxVerevkin** [comment] 2021-05-02 07:14
> Since a block contains a series of widgets built from the format string

The only block that has multiple widgets for one format string is `speedtest` (and I'm not happy with it tbh), others use just one widget for their format string. So I don't see why this approach wouldn't work (maybe I don't understand the way i3bar/swaybar handles `short_text`?).

> So another idea would be integrating this into the format string syntax as a modifier for the placeholders (like `{speed_down?}` means can be hidden).

I believe that's not possible (how to handle spaces?).

**Comment by MaxVerevkin** [comment] 2021-05-02 07:19
> is `speedtest` (and I'm not happy with it tbh)

Is `ping` highlighting *that* necessary?

**Comment by GladOSkar** [comment] 2021-05-02 08:26
Oh yeah I was testing with `speedtest` mostly so that's where I got that from.

> Is ping highlighting that necessary?

No I think I said before that I'm in favor of dropping it

**Comment by GladOSkar** [comment] 2021-05-02 10:55
Alright [here](https://github.com/GladOSkar/i3status-rust/commit/76890968e23465f7aa680a972cb93bcd56b2e0a5)'s my first, naive implementation. It does work the way I'd imagined it except that i can't really get the block to hide completely yet, not sure what's up there.

I don't think this is too much code to add to every block, but do you think there's a better way @MaxVerevkin?

**Comment by MaxVerevkin** [comment] 2021-05-02 11:11
@GladOSkar 

> i can't really get the block to hide completely yet, not sure what's up there.

I can't think of any way to accomplish this :(

> but do you think there's a better way

In order to minimize per-block code it might be a good idea to let `FormatTemplate` handle both `format` and `format_short`. I mean change
```rust
impl FormatTemplate {
    pub fn from_string(s: &str) -> Result<Self> {
```
to
```rust
impl FormatTemplate {
    pub fn from_string((s: &str, s_short: Option<&str>)) -> Result<Self> {
```
,
```rust
    pub fn render(&self, vars: &HashMap<&str, Value>) -> Result<String> {
```
to
```rust
    pub fn render(&self, vars: &HashMap<&str, Value>) -> Result<(String, Option<String>)> {
```
and
```rust
    pub fn with_text(mut self, content: String) -> Self {
```
to
```rust
    pub fn with_text(mut self, content: (String, Option<String>)) -> Self {
```

**Comment by GladOSkar** [comment] 2021-05-02 11:56
> I can't think of any way to accomplish this :(

The output widget vector would need to be empty which would be a special case for when the widget text is empty. I think that's what i missed.

> let FormatTemplate handle both format and format_short at the same time

Yeah that was what i was thinking as well. Might take a look at it but it's unlikely I'll have the time this week.

**Comment by MaxVerevkin** [comment] 2021-05-02 11:59
> The output widget vector would need to be empty which would be a special case for when the widget text is empty. I think that's what i missed.

The issue is that we don't know whether the block is switched to `short_text` or not.

**Comment by GladOSkar** [comment] 2021-05-02 12:02
Ohh yeah you're right

**Comment by GladOSkar** [comment] 2021-05-02 12:03
At this point we'd need to start querying `xrandr` for the screen width and measure the pixels of the pango output ourselves lol -.-

**Comment by MaxVerevkin** [comment] 2021-05-02 14:03
I also implemented `short_text` for some blocks [here](https://github.com/MaxVerevkin/swaystatus/commit/b5b971e781d3153b3a18908362b02f9a369d1a60). I will be able to submit a PR when https://github.com/MaxVerevkin/swaystatus/issues/4 will be resolved (probably not too soon).

Demo: 

https://user-images.githubusercontent.com/34583604/116815830-06904a00-ab68-11eb-8491-b6d84fc1fc97.mp4

**Comment by MaxVerevkin** [comment] 2021-05-02 15:07
Maybe is syntax OK?

```toml
[[block]]
block = "..."
[block.format]
full = "..."
short = "..."
```

This syntax gives ability to create a new type (let's say `BlockFormatConfig`) that would be required for `FormatTemplate::new()` to enforce `short_text` management on all the blocks that use

**Comment by GladOSkar** [comment] 2021-05-02 16:00
That looks like it would break existing configs again though, right? Or would you keep the old `format` parameter as well?

**Comment by GladOSkar** [comment] 2021-05-02 16:02
Also I don't see the need to enforce it, can't we add it to blocks progressively? The `short_text` is optional after all

**Comment by MaxVerevkin** [comment] 2021-05-02 16:09
> That looks like it would break existing configs again though, right?

No.

> Also I don't see the need to enforce it, can't we add it to blocks progressively? The short_text is optional after all

I just don't like the idea that some blocks have the ability to set short formats and some don't. This means that we have to explicitly state which block support this feature and which do not. Also, let's look at `battery` block. It has three format options. If we add short text options, we end up with six format options, which is, well, a lot.

**Comment by MaxVerevkin** [comment] 2021-05-02 16:14
> I don't see the need to enforce it

It's not like *enforcing*, it's just sort of *integrating* short text management into existing code that adds a new feature without the need to add almost any code to every block (36 files).

**Comment by MaxVerevkin** [comment] 2021-05-02 16:19
> Also I don't see the need to enforce it, can't we add it to blocks progressively? The short_text is optional after all

I guess you got me wrong. I didn't mean that specifying `short_text` would be mandatory.

**Comment by GladOSkar** [comment] 2021-05-02 17:04
No I think I understood you correctly but your argument seems sound. I'm on board 👍

**Comment by MaxVerevkin** [comment] 2021-05-02 21:02
OK, so I've implemented it in https://github.com/MaxVerevkin/swaystatus/commit/b26224dfd9940f13f5d272f93c0ebe54a57db7b2. It doesn't depend on async, so it should be easy to port (I don't have enough time for that in the near future).

**Comment by ivankovnatsky** [comment] 2021-05-04 06:16
oh wow, guys, you picked it up so fast. 

me (for now) from user perspective liking the way to set full, short formats globally for any widget.

sorry, don't have enough familiarity with the code base.

**Comment by ivankovnatsky** [comment] 2021-05-12 19:36
guys, i'm pretty happy with this feature. not sure if that suits everybody, but the implementation is way better than i anticipated. 

in general i think this is done, let me know if we need to keep it open still.

**Comment by GladOSkar** [comment] 2021-05-12 20:23
If you consider it done you can close it :)

**Comment by ivankovnatsky** [comment] 2021-05-13 05:55
guys, thanks a lot!

**Closed** 2021-05-13 05:54 UTC
Labels: feature request
