### ISSUE TITLE
Can't get SSID from Net block

### ISSUE THREAD

**Issue by MDingas** [greshake/i3status-rust#1637] opened 2022-10-11 10:11 UTC
uname -a

```
Linux user 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux
```

My ```net``` block

```
[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid}"
hide_missing = true
hide_inactive = true
```

iwgetid from ```wireless_tools``` seems to detect it just fine

```
wlp2s0    ESSID:"the-ssid"
```

The i3status-rs output for {ssid}

```
N/A
```

I recall this working on a previous installation where the interface was ```wlan0``` instead of ```wlp2s0```. Apart from that I can't think of any other change from the time it used to work.

**Comment by MaxVerevkin** [comment] 2022-10-11 10:19
Duplicate of #1607

**Closed by MaxVerevkin** 2022-10-11 10:19 UTC
