### ISSUE TITLE
Internal: requests for update should not be repeated again and again for ever.

### ISSUE THREAD

**Issue by rtxm** [greshake/i3status-rust#310] opened 2018-12-01 22:11 UTC
In https://github.com/greshake/i3status-rust/blob/287282b06316a3b4525578386ebc4dd21ead6622/src/main.rs#L227 request for updates are added to the scheduler that keeps repeating forever as soon as the block `.update` method always returns a time interval.

This affects the following blocks:

- music (each time a bus event is received);
- custom (each time you click it);
- memory (each time you click it).

This explains #290 and is not limited to the music block. It happens that the music blocks receives many more external events that are converted to requests for update internally than any other block and thus exhibits much sooner higher CPU usage.

**Comment by atheriel** [comment] 2018-12-01 22:38
Yes, this is clearly an issue, and probably the heart of #290. If anyone's keen to take on the scheduling code we're very happy to take PRs.

**Comment by rtxm** [comment] 2018-12-01 22:49
I propose not to schedule *requests for update* and process them immediately as illustrated in PR #311.

**Comment by atheriel** [comment] 2018-12-07 02:59
Has this been resolved by #311? If so, we should close the issue.

**Comment by xxxserxxx** [comment] 2020-04-30 18:00
@atheriel, I don't think so.  See #569, which I traced down to the music block -- unless what I found is unrelated to the root cause of this.

**Comment by ammgws** [comment] 2020-11-06 14:12
@rtxm @xxxserxxx With #906 the music block should not spam as many updates anymore. I haven't been able to reproduce this issue for a while (my main player has been `mpd` this whole time) so I cannot confirm whether things like #569 have been solved or not.

**Closed** 2020-11-11 14:33 UTC
Labels: future-rewrite, help wanted
