### ISSUE TITLE
Option to disable padding for formatted strings

### ISSUE THREAD

**Issue by REALERvolker1** [greshake/i3status-rust#1707] opened 2023-01-24 02:28 UTC
Currently, there are a [few ways](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html) of ensuring strings are cut off at a specified number of characters. Currently, strings are padded with spaces if they are not long enough to fit into the desired string length. There is no setting to disable or change this padding.

![image](https://user-images.githubusercontent.com/73304952/214199090-278438ad-abe0-47bb-82f5-9898158f469d.png)

Here is a slightly modified screenshot showing the desired result:

![image](https://user-images.githubusercontent.com/73304952/214199557-dc5918da-f6ad-4a73-beeb-af9a552ff578.png)

I tried to implement this myself, but this project is a bit too advanced for me right now. I think [this](https://github.com/greshake/i3status-rust/blob/f0711a9bf19edef4f9bab55deae550852a0b6cf0/src/formatting/formatter.rs#L148) has something to do with the space padding?

**Comment by MaxVerevkin** [comment] 2023-01-24 08:03
#1698 will make this possible

**Comment by GladOSkar** [comment] 2023-01-24 10:02
I think the regular `str` formatter already supports this (see `min-width` and `max-width`). `rot-str` was just intended to always occupy a fixed width.

**Comment by MaxVerevkin** [comment] 2023-02-01 14:08
Duplicate of #1624

**Closed by MaxVerevkin** 2023-02-01 14:08 UTC
