### ISSUE TITLE
Bad visualization of Net block with VPN

### ISSUE THREAD

**Issue by Giorgiofox** [greshake/i3status-rust#396] opened 2019-06-20 17:00 UTC
![i3status_vpn_problem](https://user-images.githubusercontent.com/1769743/59867071-74289800-938d-11e9-9a58-5da1dcf207ce.png)

Hello, connecting a VPN, I obtain on the same interface two IP address, and the network block show both address.. but both of them are almost unreadable. 
How I can solve it?
thanks
Giorgio

**Comment by atheriel** [comment] 2019-06-20 18:36
This is a dupe of #386 and should be fixed in master. Feel free to reopen if it does not seem to be resolved.

**Closed by atheriel** 2019-06-20 18:36 UTC
