### ISSUE TITLE
Music block not updating although the song has changed. (ncspot)

### ISSUE THREAD

**Issue by epixinvites** [greshake/i3status-rust#1124] opened 2021-03-20 06:31 UTC
I have ncspot running, and somehow I'll have to like manually Alt+Shift+R (i3 keybind) to refresh the whole thing and then the song only updates.

**Comment by ammgws** [comment] 2021-03-20 08:41
Can you see whether there are any signals being sent when `ncspot` changes tracks?
`busctl --user monitor org.mpris.MediaPlayer2 --match 'member=PropertiesChanged'`

**Comment by epixinvites** [comment] 2021-03-21 01:22
Yes I do, but my block isn't responding as normal.

**Comment by ammgws** [comment] 2021-03-21 04:47
OK I'll see if I can test ncspot using spotify free.

**Comment by epixinvites** [comment] 2021-03-21 05:47
ncspot doesnt work with spotify free, only spotify premium tho

**Comment by ammgws** [comment] 2021-03-21 09:02
That's a shame then :(

OK so does the block update if you pause the song from ncspot?

**Comment by epixinvites** [comment] 2021-03-21 09:54
nope

**Comment by ammgws** [comment] 2021-03-21 10:11
Can you add these lines and see what output you get in the terminal?

https://github.com/greshake/i3status-rust/blob/03d4fdfcc043e0c61b268bc295fe554f42d602b3/src/blocks/music.rs#L389
```rust
eprintln!("{:#?}", player);
```

https://github.com/greshake/i3status-rust/blob/03d4fdfcc043e0c61b268bc295fe554f42d602b3/src/blocks/music.rs#L397
```rust
eprintln!("{:#?}", raw_metadata);
```

**Comment by ammgws** [comment] 2021-03-21 10:59
OK I so started a Premium trial and the block works fine?

Test config:

```toml
[[block]]
block = "music"
player = "ncspot"
```

Opened ncspot, went to playlist tab and started playing random songs and the block updates accordingly (I'm on `master`).

**Comment by epixinvites** [comment] 2021-03-21 11:14
well I did have that in my config and sometimes it works sometimes it doesn't.

**Comment by ammgws** [comment] 2021-03-21 11:19
I'm not sure what else I can do to help you since I can't seem to reproduce it. The info needed would be to add those debug print statements and/or also log the output `busctl --user monitor org.mpris.MediaPlayer2 --match 'member=PropertiesChanged'` and see what is (or isn't) happening when it "doesn't work".

Or otherwise figure out if there is a way to reliably reproduce the issue (preferably within the next couple of weeks while I still have Premium)

**Comment by ammgws** [comment] 2021-03-21 11:23
Are you sure the whole bar isn't freezing? Perhaps try running a separate instance of i3status-rust in a terminal with *only* this as a config:

```toml
[[block]]
block = "music"
player = "ncspot"
```

And see if it also stops working when your main one does.

**Comment by ammgws** [comment] 2021-03-21 11:24
@benjaminBrownlee I noticed you may be using `ncspot` in an old issue (#966), if so, have you ever come across this issue?

**Comment by ammgws** [comment] 2021-03-21 11:26
@epixinvites Also can you confirm what version of i3status-rust you're running?

**Comment by epixinvites** [comment] 2021-03-21 12:33
`i3status-rs 0.14.7` I installed it via AUR, so it should be always up-to-date.

**Comment by MaxVerevkin** [comment] 2021-03-21 15:07
@epixinvites Does my rewrite of the music block work for you?

https://github.com/MaxVerevkin/i3status-rust/tree/experemental

It merges two threads into one and solves some issues I've faced.

**Comment by GrayJack** [comment] 2021-04-01 17:15
I have the same issue, just that it happens with any player, I mainly use spotify web app, but it also gets firefox and chromium when watching a video there, but the player status is frozen while other status continue to work fine.

My config:
```
[[block]]
block = "music"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"
marquee = true
marquee_interval = 1
marquee_speed = 0.5
hide_when_empty = true
format = "{avail} | {combo}"
```

**Comment by ammgws** [comment] 2021-04-02 04:15
What happens when you right click on the block when that happens?

**Comment by GrayJack** [comment] 2021-04-02 05:39
> What happens when you right click on the block when that happens?

It moves slightly

**Comment by ammgws** [comment] 2021-04-08 12:16
How easily can you reproduce this? Since I can't reproduce it at all the only thing left is to try run some debug code.

**Comment by GrayJack** [comment] 2021-04-08 13:57
It happens to me literally always, for me to reproduce it's pretty much "just lunch i3wm"

I'll be glad to help, if you put some debug code in a branch I can compile it and test it out

**Comment by ammgws** [comment] 2021-04-08 15:14
Does it also happen with the 0.14.7 release?

**Comment by GrayJack** [comment] 2021-04-08 15:56
I can try out latter today, my distribution has 0.14.7 in the repositories 😄

**Comment by tk-nguyen** [comment] 2021-04-12 05:40
> What happens when you right click on the block when that happens?

I'm having the same issue. When I right click on the block several times it changes the song correctly. I'm using the `master` branch `i3status-rs 0.20.0 (commit 759602d 2021-04-07)`.

**Comment by ammgws** [comment] 2021-04-13 10:25
Does it also occur on 0.14.7?

**Comment by tk-nguyen** [comment] 2021-04-13 11:53
Yea, it still occurs in v0.14.7 `i3status-rs 0.14.7 (commit 03d4fdf 2021-02-15)`. It has some weird behaviors though. Sometimes the block updates correctly when Spotify is in focus. When it doesn't, I have to right click the block several times to get it to update. After right clicking it updates accordingly when I manually change the songs, but doesn't change when the next songs play.

**Comment by MaxVerevkin** [comment] 2021-04-13 11:59
That's weird. Just out of curiosity: does [swaystatus](https://github.com/MaxVerevkin/swaystatus) work for you? It will probably get merged into `i3status-rust` when it'll move to `async`.

**Comment by ammgws** [comment] 2021-04-13 12:49
@GrayJack, @tk-nguyen For debugging can you try https://github.com/greshake/i3status-rust/tree/printf?

**Comment by tk-nguyen** [comment] 2021-04-13 14:37
@ammgws here they are:
```rust
new event: ppc
[src/blocks/music.rs:418] updated = false
-------------------------------------
[src/blocks/music.rs:347] players_clone.lock().expect("failed to acquire lock for `players`") = [
    Player {
        bus_name: ":1.28",
        interface_name: "org.mpris.MediaPlayer2.spotify",
        playback_status: Playing,
        ....
```
Funnily enough, with the `printf` branch the music block is working perfectly fine. Songs are updated correctly and it has marquee now :smile:! It didn't have marquee before...

**Comment by ammgws** [comment] 2021-04-13 14:43
Hmm OK the debug output is not very useful if it actually works :laughing: 

Though now it makes even less sense since the code should be exactly the same!

**Comment by GladOSkar** [comment] 2021-04-14 10:22
If the `printf`ing makes a difference maybe it's some sort of output buffering issue? No idea how this is done i rust but something like C/C++'s `setvbuf();` with `_IOLBF` or even `_IONBF`

**Comment by ammgws** [comment] 2021-04-14 11:34
> player status is frozen while other status continue to work fine

Unlikely

**Comment by GladOSkar** [comment] 2021-04-14 12:09
Oh right must have missed that

**Comment by tk-nguyen** [comment] 2021-04-17 03:28
Update: It seems when I redirect `stderr` to a log file, the music block works normally. Otherwise, it still freezes when songs change. Right-clicking the block several times will update it correctly.

**Comment by ammgws** [comment] 2021-04-17 03:57
Can you run it separately in a terminal and reproduce it there? Need to see what is happening when only the music block freezes and the others are still updating

**Comment by tk-nguyen** [comment] 2021-04-17 04:55
It only spits out this:
```rust
-------------------------------------
[src/blocks/music.rs:347] players_clone.lock().expect("failed to acquire lock for `players`") = [
    Player {
        bus_name: ":1.29",
        interface_name: "org.mpris.MediaPlayer2.spotify",
        playback_status: Playing,
        artist: Some(
            "Valencia",
        ),
        title: Some(
            "Where Did You Go?",
        ),
    },
]
new event: ppc
[src/blocks/music.rs:418] updated = false
-------------------------------------
[src/blocks/music.rs:347] players_clone.lock().expect("failed to acquire lock for `players`") = [
    Player {
        bus_name: ":1.29",
        interface_name: "org.mpris.MediaPlayer2.spotify",
        playback_status: Playing,
        artist: Some(
            "Valencia",
        ),
        title: Some(
            "Where Did You Go?",
        ),
    },
]
```
It updates normally when I manually run `i3status-rs` in another terminal window. I can't reproduce the freeze though, for whatever reasons.

**Comment by ammgws** [comment] 2021-04-17 05:02
Can you use `tee` in your i3/swaybar config to copy the output of i3status-rs rather than redirecting it? Maybe that way you can reproduce the freeze and capture the output at the same time

**Comment by epixinvites** [comment] 2021-04-17 05:45
how am i supposed to do that

**Comment by ammgws** [comment] 2021-04-17 05:50
`i3status-rs |& tee /tmp/debugi3rs`

**Comment by tk-nguyen** [comment] 2021-04-19 05:26
I've managed to reproduce to freeze. I see that the music block output is correct, but strangely the bar is not updated accordingly.
![screenshot_2021-04-19_12-23-21_644978688](https://user-images.githubusercontent.com/39090621/115185514-2d7f6280-a10a-11eb-9fc5-60a3505d4baa.png)

**Comment by ammgws** [comment] 2021-04-20 13:06
I don't even get how that is possible (that i3status is generating the correct JSON but on i3bar only the music block is frozen while the others are updating correctly)

Are you able to test with `sway`?

**Comment by ram02z** [comment] 2021-04-24 00:59
I use sway and have the same issue that @tk-nguyen described. I can post my tests tomorrow.

**Comment by ram02z** [comment] 2021-04-24 02:22
Ok, so it was working for the first few minutes flawlessly, but then it suddenly stopped. I tried switching songs and it would show the same string. By the way, that is a pattern I have noticed; works fine for a few minutes then just stops moving/updating. See images below for reference. 
> song name not updating
![20210424_03h08m21s_grim](https://user-images.githubusercontent.com/59267627/115943941-c287b000-a4aa-11eb-9562-08c24091aa41.png)
> different song loaded
![20210424_03h09m05s_grim](https://user-images.githubusercontent.com/59267627/115943943-c3204680-a4aa-11eb-9eb5-cf2ee34ad40d.png)
> Music block config
```[[block]]
block = "music"
buttons = ["prev", "play", "next"]
marquee_interval = 0
marquee_speed = 0.25
dynamic_width = true
separator = " "
on_click = "~/.local/bin/i3-quickterm mpsyt"
on_collapsed_click = "~/.local/bin/i3-quickterm mpsyt" 
interface_name_exclude = ["firefox"]
```

**Comment by ammgws** [comment] 2021-04-24 02:38
OK so at least your case is plausible; both your JSON and actual bar show the same (outdated) song. In that case can you try the https://github.com/greshake/i3status-rust/tree/printf branch and log the output. There must be some signals we are not catching/ignoring by accident that cause it to stop updating.

**Comment by ram02z** [comment] 2021-05-03 13:22
@ammgws sorry for the late response, I have been away from my sway machine. Here is the output from the printf branch.
![image](https://user-images.githubusercontent.com/59267627/116880715-40218d80-ac1a-11eb-9240-f13886b3c264.png)

> Music block config

```
block = "music"
buttons = ["prev", "play", "next"]
marquee_interval = 0
marquee_speed = 0.25
dynamic_width = true
separator = " "
on_click = "~/.local/bin/i3-quickterm mpsyt"
on_collapsed_click = "~/.local/bin/i3-quickterm mpsyt" 
interface_name_exclude = ["firefox"]
```
I have observed that the behaviour when the song doesn't update is that the playback status is shown as "Stopped", when in fact it is playing. Also, the block text gets stuck on a old song whilst rotating as you can by the pango output.

**Comment by ammgws** [comment] 2021-05-09 13:47
@ram02z Regarding the playback status not being updated, that is very interesting! And very weird behaviour with the marquee showing the old track... 

I made the debug statements more verbose in order to try catch where this is going wrong. Could you please reproduce the issue while logging all output to a file, and upload that in a gist instead of a screenshot? Need to capture the moment the block starts acting weird so I can see what MPRIS signals are being sent around then.

Also, could you confirm whether this issue still occurs with `marquee = false`? That's another important piece of info.

**Comment by ammgws** [comment] 2021-05-09 13:59
Also your config seems a bit weird - the marquee interval is way too short. When set to `0` it just spams so many updates that it end up peggings the CPU on my system.

**Comment by ram02z** [comment] 2021-05-09 20:08
@ammgws hmm, yeah I just wanted it to move faster as the default config was too slow for me. I will test it with the defaults this time around.

**Comment by ammgws** [comment] 2021-05-11 10:25
@ram02z Yeah you probably want to set it to something other than 0 in that case :laughing: 

Let me know how the debugging goes.

**Comment by ram02z** [comment] 2021-05-13 00:18
@ammgws So after trying both marquee on and off, with the rest of the music block settings on default, I couldn't reproduce the issue with marquee off. However, I was able to reproduce the issue with the marquee on. Here is the [gist](https://gist.github.com/ram02z/c199710f2214e9cb4e836590b30ea650#file-gistfile1-txt-L290) (Line 292 is where you can see that it does not update).

Let me know if you also want the debug file for the marquee off as well.

**Comment by fabianski7** [comment] 2021-06-24 03:59
I have the same problem with any player. version 0.20.1-1 installed via archlinux

The only way I managed to get it to work (without restarting the sway), was by setting a specific player, like firefox, but obviously all other players are ignored

**Comment by ammgws** [comment] 2021-06-24 12:21
Maybe I will have luck reproducing using your config.

Can you show me:

- your block config
- the output of `busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1` when you have a player running and it's not updating

**Comment by fabianski7** [comment] 2021-06-24 20:37
well, since I switched to pipewire I haven't had this problem anymore.
Anyway, here is my [block config](https://bin.disroot.org/?a91e6e7c2804d36d#61XhYKDaX7mYuXCLZuwafzgWcCDhCMwnN7va668Z5Amt) and busctl output

```
 $  busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1
org.mpris.MediaPlayer2.firefox.instance32022
org.mpris.MediaPlayer2.mpd
org.mpris.MediaPlayer2.playerctld
```

**Comment by ammgws** [comment] 2021-06-26 05:23
The audio stack should be completely unrelated to the mpris bus, so that might be a coincidence?

Unless you can reproduce out again with pulseaudio?

**Comment by ammgws** [comment] 2021-08-10 03:23
Hmm lately I have been experiencing some issues with the block, but may perhaps be a separate issue. What happens in my case is that the block just seems to randomly lose all ability to grab info from the mpris bus and ends up empty and collapsed. I am guessing all others in this thread are still experiencing their original issues?

**Comment by Ma27** [comment] 2021-08-25 15:52
It seems as if setting `dynamic_width = true` indeed fixes the issue, at least I can't reproduce this anymore after using this option.

I guess that this is because otherwise `min_width` will be set to ` MUSIC 0000000000000000000000` which *may* confuse swaybar (in my case).

**Comment by jamesmcm** [comment] 2021-10-31 21:16
This was driving me crazy with Spotify, and I think I found the issue:

In `update()`:
```rust
        let metadata = match players.first() {
            Some(m) => m,
            None => {
                debug!("No player found - setting metadata to None");
                self.current_song_widget.set_text(String::from(""));
                return Ok(None);
            }
        };
```
When there is no player (i.e. Spotify has been closed for a while) then we tell the Update scheduler to not schedule further updates.

However, this does not work for the marquee case since we need it to constantly be triggering, but the events from the song change or player change are only triggered once (they do not write to the scheduler's scheduled tasks):

e.g. on song change:

```rust
                        if updated {
                            send_clone.send(Task {
                                id,
                                update_time: Instant::now(),
                            }).unwrap();
                        }
```

But that `send` / `send_clone` is the `rx_update_requests` channel, _not_ the `ttnu` channel/scheduler scheduled events which is what we would want for the marquee (so it starts scheduled updates again).


In `main.rs`:
```rust
            recv(rx_update_requests) -> request => if let Ok(req) = request {
                // Process immediately and forget
                blocks.get_mut(req.id)
                    .internal_error("scheduler", "could not get required block")?
                    .update()?;
                protocol::print_blocks(&blocks, &shared_config)?;
            },
            // Receive update timer events
            recv(ttnu) -> _ => {
                scheduler.do_scheduled_updates(&mut blocks)?;
                // redraw the blocks, state changed
                protocol::print_blocks(&blocks, &shared_config)?;
            },
```

Note the comment on the `rx_update_requests` channel (e.g. from song change, right click) - the event is only processed once and does *not* write to scheduled updates. Note this works in the non-marquee case because the one update you do get is enough to update the block, whereas when marquee is enabled it just cycles it forward one character.

I created a PR in #1327 to address this - allowing the `update_requests` to write to the scheduler scheduled events if the block doesn't currently have any events scheduled. This means the song  change event can schedule the necessary marquee event and things can resume after the player has been closed and re-opened.

**Comment by ammgws** [comment] 2021-11-01 04:31
Excellent detective work!! This explains why I never could reproduce this since `mpd` is always available on the bus even when no songs are playing.

**Comment by ammgws** [comment] 2021-11-06 07:32
I believe #1327 should have solved this. Please re-open otherwise.

**Closed by ammgws** 2021-11-06 07:32 UTC
Labels: help wanted, need more info
