### ISSUE TITLE
net block: No SSID and signal strength for wifi device

### ISSUE THREAD

**Issue by sebastianst** [greshake/i3status-rust#1607] opened 2022-08-31 14:07 UTC
* Version: `0.22.0`
* Kernel: `5.19.4-arch1-1`
* Block configuration:
```toml
[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {speed_down;K}"
interval = 5
```
* `nmcli dev wifi list` shows SSID and strength
* `iw` is installed and
  * `iw dev wlp2s0 info` shows info, but no SSID
  * `iw dev wlp2s0 link` shows the SSID

The net block with the above configuration doesn't show the SSID or signal strength. The down speed is shown, however. I use a very similar setup and config on other laptops and it works there. Just installed it on a new laptop, where it doesn't work. Any ideas?

**Comment by Stebalien** [comment] 2022-08-31 14:30
I can confirm on the latest master. I believe it's due to a kernel update, not i3status itself.

What kernel are you running? I'm running 5.19.

**Comment by sebastianst** [comment] 2022-08-31 15:15
`5.19.4-arch1-1`

**Comment by sebastianst** [comment] 2022-08-31 15:17
I run `5.19.1` on another laptop and there it works. Will update this one and report.

**Comment by Stebalien** [comment] 2022-08-31 15:22
This happened for me when I upgraded from 5.18.19.hardened to 5.19.5.hardened (I think?). I haven't tried downgrading.

**Comment by MaxVerevkin** [comment] 2022-08-31 18:20
> `iw dev wlp2s0` info shows info

Does it show the SSID too? It stopped working for me [and some other people](https://github.com/greshake/i3status-rust/issues/1515#issuecomment-1221592108) after linux 5.18 -> 5.19 update.

Both v0.22 and latest master grab the info like SSID and signal strength via the same protocol that is used by `iw dev`, but v0.22 doesn't show signal strength if SSID is not available. This is fixed on master.

**Comment by Stebalien** [comment] 2022-08-31 18:30
- `iwgetid` works`.
- `iw dev wlp170s0 link` shows the SSID.
- `iw dev wlp170s0 info` doesn't, but I'm not sure if it's supposed to?

**Comment by MaxVerevkin** [comment] 2022-08-31 19:05
> but I'm not sure if it's supposed to?

Well, it used to... If `iw dev ... link` shows the SSID on linux 5.18 and earlier, then to some extent it is our bug.

**Comment by MaxVerevkin** [comment] 2022-09-01 07:34
On `5.18.16-arch1-1` both `iw dev ... info` and `iw dev ... link` show SSID.

**Comment by MaxVerevkin** [comment] 2022-09-01 08:25
So the SSID that is printed by `iw dev ... info` (and `i3status-rs`) comes from this attribute:

```
 * @NL80211_ATTR_SSID: SSID (binary attribute, 0..32 octets)
```

Whereas `iw dev ... link` shows this:

```
 * @NL80211_BSS_INFORMATION_ELEMENTS: binary attribute containing the
 *	raw information elements from the probe response/beacon (bin);
 *	if the %NL80211_BSS_BEACON_IES attribute is present and the data is
 *	different then the IEs here are from a Probe Response frame; otherwise
 *	they are from a Beacon frame.
 *	However, if the driver does not indicate the source of the IEs, these
 *	IEs may be from either frame subtype.
 *	If present, the @NL80211_BSS_PRESP_DATA attribute indicates that the
 *	data here is known to be from a probe response, without any heuristics.
```

**Comment by sebastianst** [comment] 2022-09-01 15:23
Can confirm here, on `5.19.4-arch1-1`, `iw dev ... info` *doesn't* show the SSID, whereas `iw dev ... link` *does* show it.

**Comment by sebastianst** [comment] 2022-09-01 15:38
Also, after updating my other laptop from `5.19.1` to `5.19.5`, it also stopped showing ssid & signal strength. Interestingly, the device name on that machine changed from the usual `wlp3s0` scheme to the old school `wlan0` scheme.

**Comment by ammgws** [comment] 2022-09-02 12:28
Are there no upstream bug reports or discussions at all? Surely someone would have said something by now?

**Comment by MaxVerevkin** [comment] 2022-09-06 21:54
Probably relevant: https://bugs.archlinux.org/task/75709

**Comment by sebastianst** [comment] 2022-09-12 07:12
> Probably relevant: https://bugs.archlinux.org/task/75709

This bug report is WPA3-specific, whereas I experience this problem with all types of wifi networks, on multiple laptops.

**Comment by sebastianst** [comment] 2022-09-29 15:00
@MaxVerevkin any new thoughts on this? I see this marked as an upstream bug, but have we clearly identified the bug? Is there an upstream bug report yet?

**Comment by SanchayanMaity** [comment] 2022-10-04 14:32
FWIW, noting my observations if it helps.

After trying out `master`, since the network manager block got dropped, I landed on this issue after switching to `net` block. SSID and signal strength were not showing up. This made me think of switching to `iwd` somehow. Right now, I only have `iwd` + `systemd-networkd` on my system. No network manager and wpa supplicant.  Both SSID and signal strength seem to be working.

Relevant output if it helps.

```
#: i3status-rs --version
i3status-rs 0.30.0 (commit 6510a913 2022-10-04)
#: uname -a
Linux core-endeavour 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux
#: iw dev wlan0 info
Interface wlan0
        ifindex 4
        wdev 0x2
        addr 2c:db:07:58:f2:f5
        ssid AsusAIMesh_5G
        type managed
        wiphy 0
        channel 48 (5240 MHz), width: 80 MHz, center1: 5210 MHz
        txpower 22.00 dBm
        multicast TXQ:
                qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                0       0       0       0       0       0       0       0               0
#: iw dev wlan0 link
Connected to 3c:7c:3f:62:f8:54 (on wlan0)
        SSID: AsusAIMesh_5G
        freq: 5240
        RX: 723750259 bytes (502436 packets)
        TX: 42856476 bytes (45997 packets)
        signal: -66 dBm
        rx bitrate: 585.1 MBit/s VHT-MCS 6 80MHz short GI VHT-NSS 2
        tx bitrate: 650.0 MBit/s VHT-MCS 7 80MHz short GI VHT-NSS 2

        bss flags:      short-slot-time
        dtim period:    3
        beacon int:     100
```
With Network manager and wpa supplicant, interface name was `wlp4s0` and now it is `wlan0`. Not sure if that makes any difference.

**Comment by danieltd** [comment] 2022-10-10 20:43
Is there a workaround that can be implemented until the upstream bug is fixed? Or perhaps i3status-rust can incorporate a fallback method for obtaining this network information if the default method fails.

**Comment by MaxVerevkin** [comment] 2022-10-11 04:21
> Is there a workaround that can be implemented until the upstream bug is fixed?

Yes, we can follow `iw dev ... link` and parse `NL80211_BSS_INFORMATION_ELEMENTS`. Or we can just parse the output of `iw dev ... link`. The first workaround is preferable, but the second is the easiest one.

**Comment by AkechiShiro** [comment] 2022-10-19 10:06
Is anyone working on a fix for this ? @MaxVerevkin

**Comment by MaxVerevkin** [comment] 2022-10-19 11:17
> Is anyone working on a fix for this ? @MaxVerevkin 
> (Still hitting this issue on Kernel 6.0.x)

I don't think anyone is working on this.

**Comment by msrd0** [comment] 2022-10-19 17:02
Is this even a problem with this repository? It works with kernel `5.15.74-1-lts` and breaks with `6.0.2` on the exact same computer. Iirc, any changes in the kernel that break userspace are considered bugs.

**Comment by AkechiShiro** [comment] 2022-10-20 05:03
So @msrd0 should we open a bug issue upstream on the kernel Bugzilla and link it here ??

**Comment by ammgws** [comment] 2022-10-20 05:11
Or report it to your distros bug tracker first

I think someone already did for arch Linux

**Comment by sebastianst** [comment] 2022-10-25 09:54
> So @msrd0 should we open a bug issue upstream on the kernel Bugzilla and link it here ??

I think this does make sense. This is clearly not a distro-specific bug but a change in the kernel API, so a upstream kernel bugzilla report should be the best way forward.

**Comment by Relected** [comment] 2022-10-31 15:16
hello, i also want to say that after updating i also had the issue where neither SSID nor strength show up for i3status-rust

im using latest stable version of i3status-rust on void linux on swaywm

kernel is 5.19.16, wifi is configured using wpa_supplicant

the down and up speed indicators work tho

**Comment by danieltd** [comment] 2022-11-22 21:40
This appears to be the upstream kernel bug report (prompted by a similar network issue in another project):

https://bugzilla.kernel.org/show_bug.cgi?id=216711

**Comment by sebastianst** [comment] 2022-11-23 11:50
> This appears to be the upstream kernel bug report (prompted by a similar network issue in another project):
> 
> https://bugzilla.kernel.org/show_bug.cgi?id=216711

Thanks for finding this! They specifically talk about WPA3 though, but the problem we all are facing seems to be independent of the Wifi connection type. E.g. I have this problem on a WPA2 network. So is it really the same problem?
Although I can say that `networkctl status wlp2s0` does indeed show `(null)` .

**Comment by msrd0** [comment] 2022-11-23 11:58
> This appears to be the upstream kernel bug report (prompted by a similar network issue in another project):
>
> https://bugzilla.kernel.org/show_bug.cgi?id=216711

I also have this problem but I'm not using systemd but network manager for connecting to wifi. `nmcli` is very well capable of displaying the SSID, but i3status-rust shows N/A.

**Comment by danieltd** [comment] 2022-11-23 15:14
@sebastianst and @msrd0 you're right. I hadn't thought about that. Perhaps this bug is related to the deeper issue going on in the kernel, but it is indeed not the specific source of what is going on with i3status-rust. I actually found a lot of networking bug reports for the new 6.x kernel series when I was looking for the one I linked to above. There must have been some significant network changes made to the kernel recently (with some oversight clearly included in those commits). Thus, the search for the offending kernel code is still on.

**Comment by danieltd** [comment] 2022-12-08 22:03
I did some searching in the Kernel bug report database today. I struck out again. Has anyone here submitted a bug report upstream for this? I am not familiar with how that process works. While browsing, I came across [this file](https://elixir.bootlin.com/linux/latest/source/net/wireless/nl80211.c) which has undergone some seemingly interesting changes in recent updates. I mostly do not understand C code, so I cannot tell for sure if any changes in this Kernel source are indeed the cause of the issue.

In the meantime, I found a crude workaround for the issue. Simply replace your net block in your i3status-rust config with the following code:

```
[[block]]
block = "custom"
command = '''iw wlan0 link | tr -d '\t' | grep . | jq -Rs 'split("\n")[:-1][] | split(": ") | {(.[0]): .[1]}' | jq -s add | jq -r '"WiFi: " + .SSID + " " + .signal' '''
interval = 5
```
Exchange `wlan0` for whatever the name of your wireless interface is.

There is [a reference online](https://www.metageek.com/training/resources/wifi-signal-strength-basics/) for what dBm means in this custom block output.

**Comment by Relected** [comment] 2023-02-06 22:51
update: this issue still persists on void linux 6.1, but this time the SSID indicator works fine when using iwd, but its broken when using wpa_supplicant, maybe this is a wpa_supplicant issue?

**Comment by cfsmp3** [comment] 2023-02-19 21:57
In previous versions, when we didn't have a SSID it was replaced with the string N/A.

We get know a verbose "failed to render the full text" with no details on why. I understand this is the result of the formatter changes, but it could definitely use some work.

@MaxVerevkin I was going to do it myself but I think the work should be on the formatter rather than here. Thoughts?

**Comment by matthewarmand** [comment] 2023-02-27 15:28
I'm also running Arch with recent kernels like many reported above, and displaying the SSID used to work fine in the `networkmanager` block, I only ran into this today when migrating to the `net` block in `0.30.x` (I'm seeing the same behavior described in #1781 whenever I try to format with `ssid`). I'm guessing that means the `networkmanager` block was using some `nm` functionality to get this to work, and not relying on whatever it is in the kernel that seems to have broken the `net` block?

**Comment by ammgws** [comment] 2023-02-27 23:40
There's a hint in here as to how nm does it:


https://github.com/i3/i3status/blob/main/src/print_wireless_info.c

**Closed** 2023-02-27 23:39 UTC
Labels: upstream bug
