### ISSUE TITLE
Hide the battery block when the device could not be found

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1668] opened 2022-11-19 18:27 UTC
I play video game using Xbox One Series game controller with the wireless dongle, so I use battery block to display the batter level of the game controller, when I'm not playing the game, the game controller will be disconnected, but when I reload i3status-rust bar, it displays 
```
UPower device could not be found
```

So could you please hide the battery block when the device could not be found ?

**Comment by MaxVerevkin** [comment] 2022-11-20 07:40
This is a known limitation of current `driver = "upower"` implementation (#1495). Can you try sysfs driver?

**Comment by c02y** [comment] 2022-11-21 07:03
The battery info of Xbox game controller of xone driver is fetched by UPower.

Is this implementation planned or impossible?

**Comment by MaxVerevkin** [comment] 2022-11-21 07:11
> The battery info of Xbox game controller of xone driver is fetched by UPower.

But it's not exposed by sysfs? I wonder where upower fetches the information from.

> Is this implementation planned or impossible?

It's possible but I doubt anyone is working on it.

**Comment by c02y** [comment] 2022-11-21 18:51
> > The battery info of Xbox game controller of xone driver is fetched by UPower.
> 
> But it's not exposed by sysfs? I wonder where upower fetches the information from.

I'm not familiar with the drivers ("sysfs", "apc_ups", or "upower"), but xone repo says `Battery reporting (UPower integration)`, so I use `UPower`, I tried battery block for the first time and only a few hours.

I tried `sysfs` driver just now, and sysfs's value and upower's value are different, `sysfs` is 75%, `upower` 70%, I don't know which one is more accurate, but `hide_block_when_device_is_not_found` is working for `sysfs` driver.

I need more time, maybe a few days, about the accurate and will let you know the result.

**Comment by c02y** [comment] 2022-11-22 17:46
UPDATE:

The battery is dead when the value is 25% (`sysfs` driver)

**Comment by ammgws** [comment] 2022-11-25 01:11
I will close this as duplicate of #1495 

As for differences between sysfs and upower, that is something out of our control, but would be interesting to find out what's going on in your case so let us know of any updates.

**Closed by ammgws** 2022-11-25 01:11 UTC
