### ISSUE TITLE
Possible memleak

### ISSUE THREAD

**Issue by Drogglbecher** [greshake/i3status-rust#176] opened 2018-04-26 07:44 UTC
Hi,

since the last update there seams to be a memleak in the status bar implementation, at least I run out of memory when using it and it stops by shutting the bar down. Could you please check this? I use version 0.9.0.

Best
Sebastian

**Comment by lausek** [comment] 2018-04-26 10:48
Which configuration are you using?

**Comment by greshake** [comment] 2018-04-27 11:09
Very interesting! Please collect more information. I've already noticed some performance leak on my system (somehow, i3bar ramps up in CPU usage although there is no increased throughput). Maybe the two are connected?

**Comment by wtfdewuno** [comment] 2018-07-16 16:18
i've seen the list of availiable themes but bad-wolf is not on it, although bad-wolf works for me .... are there any other themes?

**Comment by derekdreery** [comment] 2018-08-15 19:16
This problem cannot come from i3status-rust. It must come from one of the dependencies. Since most of the dependencies are pretty core to the rust ecosystem it would be good to figure out what causes the memory usage.

If it happens every time, then you could start it with valgrind and debug symbols, and then once it started hogging memory, kill the process and recover the valgrind output. This might tell us where the leak is coming from.

**Comment by atheriel** [comment] 2019-04-20 15:40
This was probably a dupe of #290.

**Closed by atheriel** 2019-04-20 15:40 UTC
