### ISSUE TITLE
Seperator symbols are off

### ISSUE THREAD

**Issue by Nakroma** [greshake/i3status-rust#307] opened 2018-11-28 15:16 UTC
I'm on Ubuntu 16.04, using FontAwesome. This error occurs on all themes which use the `\u{e0b2}` icon as their seperator, the seperator is weirdly off and has some kind of border/is displaced:
![](https://i.imgur.com/67J8O4T.png)
On my character map, the seperator from the Powerline Font looks fine:
![](https://i.imgur.com/KLoonnH.png)

Any idea what causes this?

**Comment by Nakroma** [comment] 2018-11-28 15:19
Using a different font-size (im currently using 8) fixes the displacement, however the arrow still looks to small: ![](https://i.imgur.com/bc439PQ.png)

**Comment by rtxm** [comment] 2018-11-28 16:53
Same thing here on Arch ; any font size below 12 shows this.

**Comment by atheriel** [comment] 2018-11-28 17:59
Dupe of #246. Unfortunately, this is beyond our ability to fix, but the thread contains a number of workarounds.

**Closed by atheriel** 2018-11-28 17:59 UTC
Labels: duplicate, fonts-and-rendering
