### ISSUE TITLE
[net] unplugged interface triggeres errors

### ISSUE THREAD

**Issue by yannick** [greshake/i3status-rust#303] opened 2018-11-14 10:14 UTC
network interfaces should simply not display when they dont exist instead of rendering the whole bar useless with an error. 
 (actually this should apply to all devices. maybe add an optional error block for failing modules or simply display an error icon)

       i have an thunderbolt dock and if i remove the laptop i currently need to change the config and add/remove the network interface...

**Comment by atheriel** [comment] 2018-11-15 21:51
Dupe of #121 and #145. We intend to fix this.

**Closed by atheriel** 2018-11-15 21:51 UTC
