### ISSUE TITLE
simply stops updating

### ISSUE THREAD

**Issue by colemickens** [greshake/i3status-rust#411] opened 2019-07-28 13:30 UTC
I don't know how to trigger this, and its sort of a hard bug report to write, but at least once a week, `i3status-rs` just entirely stops updating. I'll usually go to adjust the volume, notice it's not working, and then realize that the clock is wrong too.

Let me know if there's some other info I can provide.

**Comment by atheriel** [comment] 2019-07-29 15:05
Some info that might help us out:

1. What version you are using, and whether the issue persists if you update.
2. Your configuration, and whether the issue persists if you swap blocks in and out.

**Comment by greshake** [comment] 2019-07-31 12:13
Yea I got the same issues. I suspect it might have to do with the custom blocks, but I'm not entirely sure. The frequency of freezes is a lot higher than once a week for me, too. But I've had some issues with i3 crashing, too, so im not sure what is i3status-rust and what is i3blocks or i3s fault.

**Comment by colemickens** [comment] 2019-07-31 15:58
I have a single custom block that performs a curl. It's possible that it hangs when I transition wifi networks, etc, possibly. Now that I think about it, I had noticed that the bar would pause under certain wifi conditions. (And in my case, I'm using Sway and it more or less is always doing the right thing, hence my suspicion of i3status-rs)

I will put something in the script to force a timeout and report back.

**Comment by colemickens** [comment] 2019-07-31 15:59
Alternatively, it would be nice if I could set a timeout in the block configuration.

**Comment by colemickens** [comment] 2019-08-26 17:50
It would be nice if the execution of scripts were done in a separate thread. The current behavior of i3status causes the UI to generally be somewhat non-responsive if the script blocks take any amount of time to execute. Even under decent network conditions, a few seconds of lag can make "scroll on volume" or "scroll on brightness" to be quiet painful.

**Comment by ammgws** [comment] 2020-01-16 15:04
This is probably a duplicate of #213

**Comment by JoshMcguigan** [comment] 2020-06-21 22:57
@ammgws Do you think it is appropriate to solve this by spawning a thread per block, and allowing each block to update the main thread by sending new data back over a channel or something? I haven't looked at the source code yet, so I'm not sure if this approach would be totally impractical for some reason, just wanted to get some insight if you had already been thinking about solutions for this.

**Comment by ammgws** [comment] 2020-07-07 13:15
Probably most relevant: https://github.com/greshake/i3status-rust/issues/430

**Closed** 2020-12-16 04:53 UTC
