### ISSUE TITLE
Cannot get battery level in bluetooth block

### ISSUE THREAD

**Issue by raffifu** [greshake/i3status-rust#1740] opened 2023-02-20 17:03 UTC
I can get information about battery from Settings > Battery (Gnome)
![image](https://user-images.githubusercontent.com/22138274/220163691-b3d35759-2360-4729-a4ce-d5ec37d9b48e.png)

But i can't get it from bluetooth block, here's the output from `i3status-rs`
![image](https://user-images.githubusercontent.com/22138274/220165456-cb0fcd00-ce78-468c-b35b-c451faf268b6.png)

More info
```
$ upower -i /org/freedesktop/UPower/devices/battery_hid_bco4co45of1odeo1f_battery
  native-path:          hid-bc:4c:45:f1:de:1f-battery
  model:                Keychron K6
  power supply:         no
  updated:              Mon 20 Feb 2023 11:52:27 PM WIB (4 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          90%
    icon-name:          'battery-full-symbolic'

$ busctl introspect "org.bluez" "/org/bluez/hci0/dev_BC_4C_45_F1_DE_1F"
NAME                                TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.bluez.Device1                   interface -         -                                        -
.CancelPairing                      method    -         -                                        -
.Connect                            method    -         -                                        -
.ConnectProfile                     method    s         -                                        -
.Disconnect                         method    -         -                                        -
.DisconnectProfile                  method    s         -                                        -
.Pair                               method    -         -                                        -
.Adapter                            property  o         "/org/bluez/hci0"                        emits-change
.Address                            property  s         "BC:4C:45:F1:DE:1F"                      emits-change
.AddressType                        property  s         "public"                                 emits-change
.AdvertisingData                    property  a{yv}     -                                        emits-change
.AdvertisingFlags                   property  ay        -                                        emits-change
.Alias                              property  s         "Keychron K6"                            emits-change writable
.Appearance                         property  q         -                                        emits-change
.Blocked                            property  b         false                                    emits-change writable
.Bonded                             property  b         true                                     emits-change
.Class                              property  u         1344                                     emits-change
.Connected                          property  b         true                                     emits-change
.Icon                               property  s         "input-keyboard"                         emits-change
.LegacyPairing                      property  b         false                                    emits-change
.ManufacturerData                   property  a{qv}     -                                        emits-change
.Modalias                           property  s         "usb:v05VCasd4Fd131B"                    emits-change
.Name                               property  s         "Keychron K6"                            emits-change
.Paired                             property  b         true                                     emits-change
.RSSI                               property  n         -                                        emits-change
.ServiceData                        property  a{sv}     -                                        emits-change
.ServicesResolved                   property  b         false                                    emits-change
.Trusted                            property  b         true                                     emits-change writable
.TxPower                            property  n         -                                        emits-change
.UUIDs                              property  as        3 "00001000-0000-1000-8000-008064f7bc8d… emits-change
.WakeAllowed                        property  b         true                                     emits-change writable
org.bluez.Input1                    interface -         -                                        -
.ReconnectMode                      property  s         "device"                                 emits-change
org.freedesktop.DBus.Introspectable interface -         -                                        -
.Introspect                         method    -         s                                        -
org.freedesktop.DBus.Properties     interface -         -                                        -
.Get                                method    ss        v                                        -
.GetAll                             method    s         a{sv}                                    -
.Set                                method    ssv       -                                        -
.PropertiesChanged                  signal    sa{sv}as  -                                        -
```

Then i realize, my second output doesn't contain `.Percentage` property as in this issue https://github.com/greshake/i3status-rust/issues/1529

Is it possible to get percentage from my device with `bluetooth` block even there's no `.Percentage` property?

**Comment by MaxVerevkin** [comment] 2023-02-20 17:38
There is an open issue regarding upower fallback for bluetooth: #463. I do wonder though how upower manages to get this info while bluez fails to provide it.

**Comment by ammgws** [comment] 2023-02-21 03:25
Have you tried enabling experimental flag for bluez? Apparently it can make battery level show for some devices:

https://wiki.archlinux.org/title/bluetooth#Enabling_experimental_features

**Comment by MaxVerevkin** [comment] 2023-02-21 11:39
> Have you tried enabling experimental flag for bluez? Apparently it can make battery level show for some devices:
> 
> https://wiki.archlinux.org/title/bluetooth#Enabling_experimental_features

Wow didn't know about this. This fixed battery reporting for my headset :tada:. Added a note to the docs.

**Comment by MaxVerevkin** [comment] 2023-02-21 12:06
I edited the config and enabled both Experimental and KernelExperimental.

**Comment by MaxVerevkin** [comment] 2023-02-21 12:09
But enabling only Experimental works for me too.

**Comment by ammgws** [comment] 2023-02-21 12:45
Didn't work for my Dual Sense controller.. oh well.

@raffifu How about you?

**Comment by raffifu** [comment] 2023-02-22 09:16
Not working for my Keyboard device, But it works for my Headset device

**Comment by MaxVerevkin** [comment] 2023-02-22 23:09
Will close as a duplicate of #463

**Closed by MaxVerevkin** 2023-02-22 23:09 UTC
