### ISSUE TITLE
battery: "Not charging" state treated as "full"

### ISSUE THREAD

**Issue by GbGp** [greshake/i3status-rust#1431] opened 2022-02-12 23:32 UTC
I have a thikpad with two batteries. The charge level of each battery is always available but in some cases (e.g. battery disabled when charge is less or equal 5%) `/sys/class/power_supply/BAT#/status` will report the state `Not charging`.

I can see that after a recent change of the implementation of battery.rs (bc17fe5112bb7914ae140335569e5c212df83f7b) this case is treated as equivalent to battery full:
https://github.com/greshake/i3status-rust/blob/4c2ddf9a6b108dc51c6546713c67314e9df59242/src/blocks/battery.rs#L940-L943

This causes a minor cosmetic issue, since it will use the wrong icon (and block color) even when the actual charge level can be determined:
![bar](https://user-images.githubusercontent.com/59691707/153731814-f32cf268-e97a-4112-8d71-da7769fc6240.png)

**Comment by ammgws** [comment] 2022-02-13 06:02
I found the initial commit that introduced this behaviour in 2018: https://github.com/greshake/i3status-rust/commit/2d7e63eb81ebbbccb88899aa6cb5937ca9a5fedb, so I think it has always been like this.

I think there was another suggestion lately to add a `not_charging_format` which should allow you to customise the text that is shown, but what do suggest we do for the icon and state in this case? If it reports "Not charging" when the battery is disabled due to low charge, then an empty battery icon seems appropriate?

**Comment by MaxVerevkin** [comment] 2022-02-13 08:41
Duplicate of #1416

By the way, did you update your kernel?

**Comment by GbGp** [comment] 2022-02-13 10:53
hi,
@MaxVerevkin, I'm running on 5.16.9.

@ammgws, I'm sure I started seeing this issue recently, not 100% sure when since I've ignored it for a while but If you want I can try to bisect it. In any case removing the `status == "Not charging"` check seem to be sufficient to fix this, since the icon and battery_state are set in the other conditional branch (but I'm guessing it would to break some other corner case?)

**Comment by GladOSkar** [comment] 2022-02-13 12:42
Yes there are a lot of batteries (often aftermarket) that report as "Not charging" when they're actually full. Afaik that's more common than users actually having a non-full battery "Not charging", hence this logic. But since this is probably can't be decided deterministically, an option probably makes sense

**Comment by svenstaro** [comment] 2022-08-02 01:06
What about some stupid heuristic and make it ` if status == "Full" || (status == "Not charging" && capacity >= 50)` || capacity_is_above_full_threshold`? This would handle the case where it's not charging but above 50% which, while somewhat hacky, should be the simpler solution and it should satisfy both camps.

**Comment by svenstaro** [comment] 2022-08-03 02:25
I came up with what I think is a better fix in #1585.

**Closed** 2022-08-04 10:13 UTC
Labels: discussion
