### ISSUE TITLE
net block can't show $ssid throw Failed to render full text

### ISSUE THREAD

**Issue by raffifu** [greshake/i3status-rust#1781] opened 2023-02-25 16:11 UTC
I'm running `i3status-rs 0.30.2` on Fedora 37 and this is my configuration
```
 [[block]]
 block = "net"
 format = " $icon $ssid "
```

With above configuration when my device connected to Wi-Fi only. it display "Failed to render full text"
The output
```json
{
    "full_text": "Failed to render full text ",
    "color": "#282A36FF",
    "background": "#FF5555FF",
    "name": "6",
    "instance": "6:",
    "separator": false,
    "separator_block_width": 0,
    "markup": "pango"
}
```

But when i changed the variable to `$signal_strength`. [The Documentation](https://greshake.github.io/i3status-rust/i3status_rs/blocks/net/index.html#configuration) says `$ssid, $signal_strength and  $frequency` should be displayed in Wi-Fi connection
```
 [[block]]
 block = "net"
 format = " $icon $signal_strength $frequency"
```
it can display the value
```json
{
    "full_text": "  68%  2GHz",
    "color": "#F8F8F2FF",
    "background": "#282A36FF",
    "name": "6",
    "instance": "6:",
    "separator": false,
    "separator_block_width": 0,
    "markup": "pango"
}
```

**Comment by MaxVerevkin** [comment] 2023-02-25 16:16
Duplicate of 1607

**Closed by MaxVerevkin** 2023-02-25 16:16 UTC
